#!/usr/bin/env php
<?php
set_time_limit(0);

$_ENV['HOME'] = getenv('HOME');

if (file_exists(__DIR__.'/vendor/autoload.php')) {
    require __DIR__.'/vendor/autoload.php';
} else {
    require __DIR__.'/../../autoload.php';
}

$title = '  _____ __    ___    ____ ______  __ ____ ____ __    ____
 / ___// /   / _ |  / __// __/\ \/ // __//  _// /   / __/
/ /__ / /__ / __ | _\ \ _\ \   \  // _/ _/ / / /__ / _/
\___//____//_/ |_|/___//___/   /_//_/  /___//____//___/  ';


$application = new Symfony\Component\Console\Application($title, '0.3.0');
$application->addCommands([
    new \Onema\ClassyFile\Command\GenerateClassesFromFileCommand(),
]);
$application->run();
