#!/usr/bin/env php
<?php
set_time_limit(0);

$_ENV['HOME'] = getenv('HOME');

if (!defined('PHP_VERSION_ID') || PHP_VERSION_ID < 50400) {
    fwrite(STDERR, "PHP needs to be a minimum version of PHP 5.4.0\n");
    exit(1);
}

if (file_exists(__DIR__.'/vendor/autoload.php')) {
    require __DIR__.'/vendor/autoload.php';
} else {
    // it was installed via composer
    require __DIR__.'/../../autoload.php';
}

use Onema\ClassyFile\Console\Application;

$application = new Application();
$application->run();
