<?php
/*
 * This file is part of the Onema {classyfile} Package. 
 * For the full copyright and license information, 
 * please view the LICENSE file that was distributed 
 * with this source code.
 */

namespace Onema\ClassyFile\Template;

/**
 * BasicClassTemplate - Class to generate a basic template.
 *
 * @author Juan Manuel Torres <kinojman@gmail.com>
 * @copyright (c) 2015, onema.io
 */
class BasicClassTemplate
{
    /**
     * @var string
     */
    private $topComment;

    public function __construct ($topComment = null)
    {
        if (!isset($topComment)) {
            $date = new \DateTime();
            $this->topComment = <<<EOT
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) {$date->format('Y')}, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */
EOT;
        } else {
            $this->topComment = $topComment;
        }
    }
    public function getTemplate ($namespace, $uses, $comments, $code)
    {
        return '<?php'.
        PHP_EOL.
        $this->topComment.
        PHP_EOL.
        $namespace.
        PHP_EOL.
        $uses.
        PHP_EOL.
        $comments.
        PHP_EOL.
        $code.
        PHP_EOL;
    }
}
